// Shared vibe taxonomy — used by the vibe finder in every section.
const VIBES = [
  { id: "cozy",       label: "🧸 Cozy & comforting" },
  { id: "adrenaline", label: "⚡ Adrenaline rush" },
  { id: "mindbending",label: "🌀 Mind-bending" },
  { id: "emotional",  label: "😭 Emotional" },
  { id: "funny",      label: "😂 Laugh out loud" },
  { id: "scary",      label: "👻 Spine-chilling" },
  { id: "epic",       label: "🗡️ Epic adventure" },
  { id: "dark",       label: "🌑 Dark & gritty" },
  { id: "nostalgic",  label: "📼 Nostalgic" },
  { id: "romantic",   label: "💘 Romantic" },
  { id: "chill",      label: "🌊 Chill & relaxing" },
];

const SECTIONS = {
  movies: { label: "Movies",   icon: "🎬", listName: "Watchlist", verb: "Watched" },
  tv:     { label: "TV Shows", icon: "📺", listName: "Watchlist", verb: "Watched" },
  games:  { label: "Games",    icon: "🎮", listName: "Playlist",  verb: "Played" },
};

const CATALOG = [
  // ---------------- Movies ----------------
  { id: "m01", type: "movies", title: "The Grand Budapest Hotel", year: 2014, genres: ["Comedy", "Drama"], vibes: ["cozy", "funny", "nostalgic"] },
  { id: "m02", type: "movies", title: "Mad Max: Fury Road", year: 2015, genres: ["Action", "Sci-Fi"], vibes: ["adrenaline", "epic", "dark"] },
  { id: "m03", type: "movies", title: "Inception", year: 2010, genres: ["Sci-Fi", "Thriller"], vibes: ["mindbending", "adrenaline", "epic"] },
  { id: "m04", type: "movies", title: "Eternal Sunshine of the Spotless Mind", year: 2004, genres: ["Romance", "Sci-Fi"], vibes: ["emotional", "romantic", "mindbending"] },
  { id: "m05", type: "movies", title: "Spirited Away", year: 2001, genres: ["Animation", "Fantasy"], vibes: ["cozy", "epic", "emotional"] },
  { id: "m06", type: "movies", title: "Hereditary", year: 2018, genres: ["Horror"], vibes: ["scary", "dark"] },
  { id: "m07", type: "movies", title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, genres: ["Fantasy", "Adventure"], vibes: ["epic", "nostalgic", "emotional"] },
  { id: "m08", type: "movies", title: "Superbad", year: 2007, genres: ["Comedy"], vibes: ["funny", "nostalgic"] },
  { id: "m09", type: "movies", title: "Blade Runner 2049", year: 2017, genres: ["Sci-Fi", "Noir"], vibes: ["dark", "mindbending", "chill"] },
  { id: "m10", type: "movies", title: "Paddington 2", year: 2017, genres: ["Family", "Comedy"], vibes: ["cozy", "funny", "emotional"] },
  { id: "m11", type: "movies", title: "Whiplash", year: 2014, genres: ["Drama", "Music"], vibes: ["adrenaline", "dark", "emotional"] },
  { id: "m12", type: "movies", title: "Before Sunrise", year: 1995, genres: ["Romance", "Drama"], vibes: ["romantic", "chill", "emotional"] },
  { id: "m13", type: "movies", title: "Parasite", year: 2019, genres: ["Thriller", "Drama"], vibes: ["dark", "mindbending", "funny"] },
  { id: "m14", type: "movies", title: "The Thing", year: 1982, genres: ["Horror", "Sci-Fi"], vibes: ["scary", "dark", "nostalgic"] },
  { id: "m15", type: "movies", title: "Everything Everywhere All at Once", year: 2022, genres: ["Sci-Fi", "Comedy"], vibes: ["mindbending", "emotional", "funny"] },
  { id: "m16", type: "movies", title: "My Neighbor Totoro", year: 1988, genres: ["Animation", "Family"], vibes: ["cozy", "chill", "nostalgic"] },
  { id: "m17", type: "movies", title: "Dune: Part Two", year: 2024, genres: ["Sci-Fi", "Adventure"], vibes: ["epic", "adrenaline", "dark"] },
  { id: "m18", type: "movies", title: "La La Land", year: 2016, genres: ["Musical", "Romance"], vibes: ["romantic", "emotional", "nostalgic"] },

  // ---------------- TV Shows ----------------
  { id: "t01", type: "tv", title: "Breaking Bad", year: 2008, genres: ["Crime", "Drama"], vibes: ["dark", "adrenaline", "mindbending"] },
  { id: "t02", type: "tv", title: "The Office (US)", year: 2005, genres: ["Comedy"], vibes: ["funny", "cozy", "nostalgic"] },
  { id: "t03", type: "tv", title: "Severance", year: 2022, genres: ["Sci-Fi", "Thriller"], vibes: ["mindbending", "dark"] },
  { id: "t04", type: "tv", title: "The Great British Bake Off", year: 2010, genres: ["Reality", "Cooking"], vibes: ["cozy", "chill", "funny"] },
  { id: "t05", type: "tv", title: "Stranger Things", year: 2016, genres: ["Sci-Fi", "Horror"], vibes: ["nostalgic", "scary", "adrenaline"] },
  { id: "t06", type: "tv", title: "Fleabag", year: 2016, genres: ["Comedy", "Drama"], vibes: ["funny", "emotional", "dark"] },
  { id: "t07", type: "tv", title: "Game of Thrones", year: 2011, genres: ["Fantasy", "Drama"], vibes: ["epic", "dark", "adrenaline"] },
  { id: "t08", type: "tv", title: "Avatar: The Last Airbender", year: 2005, genres: ["Animation", "Fantasy"], vibes: ["epic", "cozy", "nostalgic"] },
  { id: "t09", type: "tv", title: "Black Mirror", year: 2011, genres: ["Sci-Fi", "Anthology"], vibes: ["mindbending", "dark", "scary"] },
  { id: "t10", type: "tv", title: "Ted Lasso", year: 2020, genres: ["Comedy", "Sports"], vibes: ["cozy", "funny", "emotional"] },
  { id: "t11", type: "tv", title: "The Haunting of Hill House", year: 2018, genres: ["Horror", "Drama"], vibes: ["scary", "emotional", "dark"] },
  { id: "t12", type: "tv", title: "Normal People", year: 2020, genres: ["Romance", "Drama"], vibes: ["romantic", "emotional", "chill"] },
  { id: "t13", type: "tv", title: "Arcane", year: 2021, genres: ["Animation", "Fantasy"], vibes: ["epic", "dark", "emotional"] },
  { id: "t14", type: "tv", title: "Seinfeld", year: 1989, genres: ["Comedy"], vibes: ["funny", "nostalgic", "chill"] },
  { id: "t15", type: "tv", title: "Chernobyl", year: 2019, genres: ["Drama", "History"], vibes: ["dark", "emotional"] },
  { id: "t16", type: "tv", title: "Bluey", year: 2018, genres: ["Animation", "Family"], vibes: ["cozy", "funny", "chill"] },
  { id: "t17", type: "tv", title: "True Detective", year: 2014, genres: ["Crime", "Mystery"], vibes: ["dark", "mindbending", "scary"] },
  { id: "t18", type: "tv", title: "One Piece", year: 1999, genres: ["Anime", "Adventure"], vibes: ["epic", "funny", "emotional"] },

  // ---------------- Games ----------------
  { id: "g01", type: "games", title: "Stardew Valley", year: 2016, genres: ["Farming Sim", "RPG"], vibes: ["cozy", "chill", "nostalgic"] },
  { id: "g02", type: "games", title: "DOOM Eternal", year: 2020, genres: ["FPS", "Action"], vibes: ["adrenaline", "dark"] },
  { id: "g03", type: "games", title: "Outer Wilds", year: 2019, genres: ["Exploration", "Puzzle"], vibes: ["mindbending", "emotional", "epic"] },
  { id: "g04", type: "games", title: "The Last of Us Part II", year: 2020, genres: ["Action", "Adventure"], vibes: ["emotional", "dark", "adrenaline"] },
  { id: "g05", type: "games", title: "Untitled Goose Game", year: 2019, genres: ["Puzzle", "Comedy"], vibes: ["funny", "chill", "cozy"] },
  { id: "g06", type: "games", title: "Resident Evil 7", year: 2017, genres: ["Horror", "Survival"], vibes: ["scary", "dark", "adrenaline"] },
  { id: "g07", type: "games", title: "The Legend of Zelda: Breath of the Wild", year: 2017, genres: ["Adventure", "Open World"], vibes: ["epic", "chill", "cozy"] },
  { id: "g08", type: "games", title: "Elden Ring", year: 2022, genres: ["Action RPG", "Souls-like"], vibes: ["epic", "dark", "adrenaline"] },
  { id: "g09", type: "games", title: "Animal Crossing: New Horizons", year: 2020, genres: ["Life Sim"], vibes: ["cozy", "chill"] },
  { id: "g10", type: "games", title: "Hades", year: 2020, genres: ["Roguelike", "Action"], vibes: ["adrenaline", "epic", "funny"] },
  { id: "g11", type: "games", title: "Portal 2", year: 2011, genres: ["Puzzle", "Sci-Fi"], vibes: ["mindbending", "funny", "nostalgic"] },
  { id: "g12", type: "games", title: "Red Dead Redemption 2", year: 2018, genres: ["Action", "Western"], vibes: ["epic", "emotional", "chill"] },
  { id: "g13", type: "games", title: "Silent Hill 2", year: 2001, genres: ["Horror", "Psychological"], vibes: ["scary", "dark", "mindbending"] },
  { id: "g14", type: "games", title: "It Takes Two", year: 2021, genres: ["Co-op", "Platformer"], vibes: ["funny", "romantic", "cozy"] },
  { id: "g15", type: "games", title: "Disco Elysium", year: 2019, genres: ["RPG", "Mystery"], vibes: ["mindbending", "dark", "funny"] },
  { id: "g16", type: "games", title: "Super Mario 64", year: 1996, genres: ["Platformer"], vibes: ["nostalgic", "funny", "epic"] },
  { id: "g17", type: "games", title: "Journey", year: 2012, genres: ["Adventure", "Art"], vibes: ["chill", "emotional", "epic"] },
  { id: "g18", type: "games", title: "Baldur's Gate 3", year: 2023, genres: ["RPG", "Fantasy"], vibes: ["epic", "funny", "romantic"] },
];
